-- Creating dimensions

CREATE TABLE BOOKINGMONTHDIM AS
SELECT DISTINCT TO_CHAR(BOOKINGDATE, 'YYYYMM') AS BOOKINGMONTHID,
       TO_CHAR(BOOKINGDATE, 'MM') AS BOOKINGMONTH,
       TO_CHAR(BOOKINGDATE, 'YYYY') AS BOOKINGYEAR
FROM BOOKING;

CREATE TABLE FACULTYDIM AS
SELECT DISTINCT FACULTYID, FACULTYNAME
FROM FACULTY;

CREATE TABLE AGEGROUPDIM (
    AGEGROUPID NUMBER PRIMARY KEY,
    AGEGROUPDESCRIPTION VARCHAR2(50) NOT NULL,
    MINIMUMAGE NUMBER NOT NULL,
    MAXIMUMAGE NUMBER NOT NULL
);

INSERT INTO AGEGROUPDIM VALUES (1, 'Young Adults', 18, 35);
INSERT INTO AGEGROUPDIM VALUES (2, 'Middle-Aged Adults', 36, 59);
INSERT INTO AGEGROUPDIM VALUES (3, 'Old-Aged Adults', 60, 999);

CREATE TABLE CARBODYDIM AS
SELECT ROW_NUMBER() OVER (ORDER BY CARBODYTYPE) AS CARBODYID,
    CARBODYTYPE,
    NUMSEATS
FROM
(
    SELECT DISTINCT CARBODYTYPE, NUMSEATS
    FROM CAR
);

CREATE TABLE MAINTENANCETYPEDIM AS
SELECT DISTINCT MAINTENANCETYPE AS MAINTENANCETYPEID, MAINTENANCEDESCRIPTION
FROM MAINTENANCETYPE;

CREATE TABLE RESEARCHCENTERDIM AS
SELECT DISTINCT CENTERID, CENTERNAME
FROM RESEARCHCENTER;

CREATE TABLE TEAMCENTERBRIDGE AS
SELECT DISTINCT TEAMID, CENTERID
FROM BELONGTO;

CREATE TABLE MAINTENANCETEAMDIM AS
SELECT MT.TEAMID,
    LISTAGG(BT.CENTERID, '_') WITHIN GROUP (ORDER BY BT.CENTERID) AS CENTERGROUPLIST,
    COUNT(BT.CENTERID) AS CENTERCOUNT,
    1.0/COUNT(BT.CENTERID) AS CENTERWEIGHTFACTOR
FROM MAINTENANCETEAM MT JOIN (SELECT DISTINCT TEAMID, CENTERID FROM BELONGTO) BT ON MT.TEAMID = BT.TEAMID
GROUP BY MT.TEAMID;

SELECT * FROM BELONGTO
ORDER BY TEAMID, CENTERID;

CREATE TABLE ZONEDIM AS
SELECT DISTINCT ACCIDENTZONE AS ZONEID
FROM ACCIDENTINFO;

CREATE TABLE ERRORDIM AS
SELECT DISTINCT ERRORCODE, ERRORMESSAGE
FROM ERROR;

-- CREATE TABLE DAMAGESEVERITYDIM AS
-- SELECT ROW_NUMBER() OVER (ORDER BY CAR_DAMAGE_SEVERITY) AS DAMAGESEVERITYID,
--     CAR_DAMAGE_SEVERITY AS DESCRIPTION
-- FROM
-- (
--     SELECT DISTINCT CAR_DAMAGE_SEVERITY
--     FROM ACCIDENTINFO
-- );

-- Manually creating DAMAGESEVERITYDIM table so I can order the severity levels correctly
SELECT DISTINCT CAR_DAMAGE_SEVERITY
FROM ACCIDENTINFO;

CREATE TABLE DAMAGESEVERITYDIM (
    DAMAGESEVERITYID NUMBER PRIMARY KEY,
    DESCRIPTION VARCHAR2(50) NOT NULL
);

INSERT INTO DAMAGESEVERITYDIM VALUES (1, 'No damage');
INSERT INTO DAMAGESEVERITYDIM VALUES (2, 'Very minor damage');
INSERT INTO DAMAGESEVERITYDIM VALUES (3, 'Minor damage');
INSERT INTO DAMAGESEVERITYDIM VALUES (4, 'Moderate damage');
INSERT INTO DAMAGESEVERITYDIM VALUES (5, 'Severe damage');

SELECT * FROM DAMAGESEVERITYDIM;

CREATE TABLE CARDIM AS
SELECT REGISTRATIONNO,
    CARMODEL,
    MANUFACTURINGYEAR,
    CARBODYTYPE,
    NUMSEATS
FROM CAR;

COMMIT;

-- Adding primary keys

ALTER TABLE BOOKINGMONTHDIM ADD PRIMARY KEY (BOOKINGMONTHID);
ALTER TABLE FACULTYDIM ADD PRIMARY KEY (FACULTYID);
ALTER TABLE CARBODYDIM ADD PRIMARY KEY (CARBODYID);
ALTER TABLE MAINTENANCETYPEDIM ADD PRIMARY KEY (MAINTENANCETYPEID);
ALTER TABLE RESEARCHCENTERDIM ADD PRIMARY KEY (CENTERID);
ALTER TABLE TEAMCENTERBRIDGE ADD PRIMARY KEY (TEAMID, CENTERID);
ALTER TABLE MAINTENANCETEAMDIM ADD PRIMARY KEY (TEAMID);
ALTER TABLE ZONEDIM ADD PRIMARY KEY (ZONEID);
ALTER TABLE ERRORDIM ADD PRIMARY KEY (ERRORCODE);
ALTER TABLE CARDIM ADD PRIMARY KEY (REGISTRATIONNO);

-- Adding foreign keys

ALTER TABLE TEAMCENTERBRIDGE ADD CONSTRAINT FK_TEAMCENTERBRIDGE_TEAMID FOREIGN KEY (TEAMID) REFERENCES MAINTENANCETEAMDIM(TEAMID);
ALTER TABLE TEAMCENTERBRIDGE ADD CONSTRAINT FK_TEAMCENTERBRIDGE_CENTERID FOREIGN KEY (CENTERID) REFERENCES RESEARCHCENTERDIM(CENTERID);

-- BookingFact table

CREATE TABLE TEMPBOOKINGFACT AS
SELECT B.BOOKINGID,
    TO_CHAR(B.BOOKINGDATE, 'YYYYMM') AS BOOKINGMONTHID,
    P.FACULTYID,
    P.PASSENGERAGE,
    C.CARBODYTYPE,
    C.NUMSEATS
FROM BOOKING B
JOIN PASSENGER P ON B.PASSENGERID = P.PASSENGERID
JOIN CAR C ON B.REGISTRATIONNO = C.REGISTRATIONNO;

CREATE TABLE BOOKINGFACT AS
SELECT TBF.BOOKINGMONTHID,
    TBF.FACULTYID,
    AG.AGEGROUPID,
    CB.CARBODYID,
    COUNT(TBF.BOOKINGID) AS NUMBEROFBOOKINGS
FROM TEMPBOOKINGFACT TBF
JOIN AGEGROUPDIM AG ON TBF.PASSENGERAGE >= AG.MINIMUMAGE AND TBF.PASSENGERAGE <= AG.MAXIMUMAGE
JOIN CARBODYDIM CB ON TBF.CARBODYTYPE = CB.CARBODYTYPE AND TBF.NUMSEATS = CB.NUMSEATS
GROUP BY TBF.BOOKINGMONTHID, TBF.FACULTYID, AG.AGEGROUPID, CB.CARBODYID;

SELECT * FROM BOOKINGFACT;
SELECT COUNT(*) FROM Booking;
SELECT NVL(SUM(NumberOfBookings), 0) FROM BookingFact;

ALTER TABLE BOOKINGFACT ADD PRIMARY KEY (BOOKINGMONTHID, FACULTYID, AGEGROUPID, CARBODYID);
ALTER TABLE BOOKINGFACT ADD CONSTRAINT FK_BOOKINGFACT_BOOKINGMONTHID FOREIGN KEY (BOOKINGMONTHID) REFERENCES BOOKINGMONTHDIM(BOOKINGMONTHID);
ALTER TABLE BOOKINGFACT ADD CONSTRAINT FK_BOOKINGFACT_FACULTYID FOREIGN KEY (FACULTYID) REFERENCES FACULTYDIM(FACULTYID);
ALTER TABLE BOOKINGFACT ADD CONSTRAINT FK_BOOKINGFACT_AGEGROUPID FOREIGN KEY (AGEGROUPID) REFERENCES AGEGROUPDIM(AGEGROUPID);
ALTER TABLE BOOKINGFACT ADD CONSTRAINT FK_BOOKINGFACT_CARBODYID FOREIGN KEY (CARBODYID) REFERENCES CARBODYDIM(CARBODYID);

-- MaintenanceFact table

CREATE TABLE TEMPMAINTENANCEFACT AS
SELECT M.MAINTENANCEID,
    M.MAINTENANCECOST,
    M.MAINTENANCETYPE AS MAINTENANCETYPEID,
    M.TEAMID,
    C.CARBODYTYPE,
    C.NUMSEATS
FROM MAINTENANCE M
JOIN CAR C ON M.REGISTRATIONNO = C.REGISTRATIONNO;

CREATE TABLE MAINTENANCEFACT AS
SELECT TMF.MAINTENANCETYPEID,
    TMF.TEAMID,
    C.CARBODYID,
    COUNT(TMF.MAINTENANCEID) AS NUMBEROFMAINTENANCE,
    SUM(TMF.MAINTENANCECOST) AS TOTALMAINTENANCECOST
FROM TEMPMAINTENANCEFACT TMF
JOIN CARBODYDIM C ON TMF.CARBODYTYPE = C.CARBODYTYPE AND TMF.NUMSEATS = C.NUMSEATS
GROUP BY TMF.MAINTENANCETYPEID, TMF.TEAMID, C.CARBODYID;

SELECT * FROM MAINTENANCEFACT;

SELECT COUNT(*) FROM Maintenance;
SELECT NVL(SUM(NumberOfMaintenance), 0) FROM MaintenanceFact;

SELECT NVL(SUM(MaintenanceCost), 0) FROM Maintenance;
SELECT NVL(SUM(TotalMaintenanceCost), 0) FROM MaintenanceFact;

ALTER TABLE MAINTENANCEFACT ADD PRIMARY KEY (MAINTENANCETYPEID, TEAMID, CARBODYID);
ALTER TABLE MAINTENANCEFACT ADD CONSTRAINT FK_MAINTENANCEFACT_MAINTENANCETYPEID FOREIGN KEY (MAINTENANCETYPEID) REFERENCES MAINTENANCETYPEDIM(MAINTENANCETYPEID);
ALTER TABLE MAINTENANCEFACT ADD CONSTRAINT FK_MAINTENANCEFACT_TEAMID FOREIGN KEY (TEAMID) REFERENCES MAINTENANCETEAMDIM(TEAMID);
ALTER TABLE MAINTENANCEFACT ADD CONSTRAINT FK_MAINTENANCEFACT_CARBODYID FOREIGN KEY (CARBODYID) REFERENCES CARBODYDIM(CARBODYID);

-- AccidentFact table

CREATE TABLE TEMPACCIDENTFACT AS
SELECT AI.ACCIDENTID,
    CA.REGISTRATIONNO,
    AI.ACCIDENTZONE AS ZONEID,
    AI.ERRORCODE,
    AI.CAR_DAMAGE_SEVERITY
FROM ACCIDENTINFO AI
JOIN CARACCIDENT CA ON AI.ACCIDENTID = CA.ACCIDENTID;


CREATE TABLE ACCIDENTFACT AS
SELECT TAF.REGISTRATIONNO,
    TAF.ZONEID,
    DS.DAMAGESEVERITYID,
    TAF.ERRORCODE,
    COUNT(TAF.ACCIDENTID) AS NUMBEROFACCIDENTS
FROM TEMPACCIDENTFACT TAF
JOIN DAMAGESEVERITYDIM DS ON TAF.CAR_DAMAGE_SEVERITY = DS.DESCRIPTION
GROUP BY TAF.REGISTRATIONNO, TAF.ZONEID, DS.DAMAGESEVERITYID, TAF.ERRORCODE;

ALTER TABLE ACCIDENTFACT ADD PRIMARY KEY (REGISTRATIONNO, ZONEID, DAMAGESEVERITYID, ERRORCODE);
ALTER TABLE ACCIDENTFACT ADD CONSTRAINT FK_ACCIDENTFACT_REGISTRATIONNO FOREIGN KEY (REGISTRATIONNO) REFERENCES CARDIM(REGISTRATIONNO);
ALTER TABLE ACCIDENTFACT ADD CONSTRAINT FK_ACCIDENTFACT_ZONEID FOREIGN KEY (ZONEID) REFERENCES ZONEDIM(ZONEID);
ALTER TABLE ACCIDENTFACT ADD CONSTRAINT FK_ACCIDENTFACT_DAMAGESEVERITYID FOREIGN KEY (DAMAGESEVERITYID) REFERENCES DAMAGESEVERITYDIM(DAMAGESEVERITYID);

SELECT COUNT(*)
FROM CarAccident ca
JOIN AccidentInfo ai ON ai.AccidentID = ca.AccidentID;
SELECT NVL(SUM(NumberOfAccidents), 0) FROM AccidentFact;


