-- getting the tables
create table FACULTY as select * from moncity.FACULTY;
create table RESEARCHCENTER as select * from moncity.RESEARCHCENTER;
create table PASSENGER as select * from moncity.PASSENGER;
create table ERROR as select * from moncity.ERROR;
create table MAINTENANCETYPE as select * from moncity.MAINTENANCETYPE;
create table BOOKING as select * from moncity.BOOKING;
create table CAR as select * from moncity.CAR;
create table MAINTENANCE as select * from moncity.MAINTENANCE;
create table ACCIDENTINFO as select * from moncity.ACCIDENTINFO;
create table CARACCIDENT as select * from moncity.CARACCIDENT;
create table MAINTENANCETEAM as select * from moncity.MAINTENANCETEAM;
create table BELONGTO as select * from moncity.BELONGTO;

select * from FACULTY;
select * from RESEARCHCENTER;
select * from PASSENGER;
select * from ERROR;
select * from MAINTENANCETYPE;
select * from BOOKING;
select * from CAR;
select * from MAINTENANCE;
select * from ACCIDENTINFO;
select * from CARACCIDENT;
select * from MAINTENANCETEAM;
select * from BELONGTO;

SELECT 'BOOKING' TABLE_NAME, COUNT(*) ROW_COUNT FROM BOOKING
UNION ALL
SELECT 'MAINTENANCE', COUNT(*) FROM MAINTENANCE
UNION ALL
SELECT 'ACCIDENTINFO', COUNT(*) FROM ACCIDENTINFO
UNION ALL
SELECT 'CARACCIDENT', COUNT(*) FROM CARACCIDENT
UNION ALL
SELECT 'PASSENGER', COUNT(*) FROM PASSENGER
UNION ALL
SELECT 'CAR', COUNT(*) FROM CAR
UNION ALL
SELECT 'FACULTY', COUNT(*) FROM FACULTY
UNION ALL
SELECT 'MAINTENANCETEAM', COUNT(*) FROM MAINTENANCETEAM
UNION ALL
SELECT 'BELONGTO', COUNT(*) FROM BELONGTO
UNION ALL
SELECT 'RESEARCHCENTER', COUNT(*) FROM RESEARCHCENTER
UNION ALL
SELECT 'ERROR', COUNT(*) FROM ERROR
UNION ALL
SELECT 'MAINTENANCETYPE', COUNT(*) FROM MAINTENANCETYPE;

-- Checking for duplicate PKs in the tables

SELECT BOOKINGID, COUNT(*)
FROM BOOKING
GROUP BY BOOKINGID
HAVING COUNT(*) > 1;

SELECT MAINTENANCEID, COUNT(*)
FROM MAINTENANCE
GROUP BY MAINTENANCEID
HAVING COUNT(*) > 1;

SELECT ACCIDENTID, COUNT(*)
FROM ACCIDENTINFO
GROUP BY ACCIDENTID
HAVING COUNT(*) > 1;

SELECT FACULTYID, COUNT(*)
FROM FACULTY
GROUP BY FACULTYID
HAVING COUNT(*) > 1;

SELECT CENTERID, COUNT(*)
FROM RESEARCHCENTER
GROUP BY CENTERID
HAVING COUNT(*) > 1;

SELECT ERRORCODE, COUNT(*)
FROM ERROR
GROUP BY ERRORCODE
HAVING COUNT(*) > 1;

SELECT MAINTENANCETYPE, COUNT(*)
FROM MAINTENANCETYPE
GROUP BY MAINTENANCETYPE
HAVING COUNT(*) > 1;

SELECT REGISTRATIONNO, COUNT(*)
FROM CAR
GROUP BY REGISTRATIONNO
HAVING COUNT(*) > 1;

SELECT TEAMID, COUNT(*)
FROM MAINTENANCETEAM
GROUP BY TEAMID
HAVING COUNT(*) > 1;

SELECT PASSENGERID, COUNT(*)
FROM PASSENGER
GROUP BY PASSENGERID
HAVING COUNT(*) > 1;

-- CARACCIDENT is identified by the car/accident pair
SELECT REGISTRATIONNO, ACCIDENTID, COUNT(*)
FROM CARACCIDENT
GROUP BY REGISTRATIONNO, ACCIDENTID
HAVING COUNT(*) > 1;

-- BELONGTO is identified by the team/centre pair
SELECT TEAMID, CENTERID, COUNT(*)
FROM BELONGTO
GROUP BY TEAMID, CENTERID
HAVING COUNT(*) > 1;

-- Looking at the booking ID duplicate for T1218
SELECT *
FROM BOOKING
WHERE BOOKINGID = 'T1218';

-- Getting the exact date and time for booking T1218
SELECT to_char(BOOKINGDATE, 'YYYY-MM-DD HH24:MI:SS') as BOOKINGDATE
FROM BOOKING
WHERE BOOKINGID = 'T1218';

-- Deleting one of the duplicate bookings ID T1218
DELETE FROM BOOKING
WHERE ROWID NOT IN (
    SELECT MIN(ROWID)
    FROM BOOKING
    GROUP BY BOOKINGID
);

COMMIT;

-- Checking for invalid FKs

-- SELECT *
-- FROM <<TABLE 1>>
-- WHERE <<FK COLUMN>> NOT IN (
--     SELECT <<PK COLUMN>>
--     FROM <<TABLE 2>>
-- );

-- Passenger -> Faculty
SELECT *
FROM PASSENGER
WHERE FACULTYID NOT IN (
    SELECT FACULTYID
    FROM FACULTY
);

-- Booking -> Passenger
SELECT *
FROM BOOKING
WHERE PASSENGERID NOT IN (
    SELECT PASSENGERID
    FROM PASSENGER
);

-- Booking -> Car
SELECT *
FROM BOOKING
WHERE REGISTRATIONNO NOT IN (
    SELECT REGISTRATIONNO
    FROM CAR
);

-- Maintenance -> Car
SELECT *
FROM MAINTENANCE
WHERE REGISTRATIONNO NOT IN (
    SELECT REGISTRATIONNO
    FROM CAR
);

-- Maintenance -> MaintenanceType
SELECT *
FROM MAINTENANCE
WHERE MAINTENANCETYPE NOT IN (
    SELECT MAINTENANCETYPE
    FROM MAINTENANCETYPE
);

-- Maintenance -> MaintenanceTeam
SELECT *
FROM MAINTENANCE
WHERE TEAMID NOT IN (
    SELECT TEAMID
    FROM MAINTENANCETEAM
);

-- AccidentInfo -> Error
SELECT *
FROM ACCIDENTINFO
WHERE ERRORCODE NOT IN (
    SELECT ERRORCODE
    FROM ERROR
);

-- CarAccident -> AccidentInfo
SELECT *
FROM CARACCIDENT
WHERE ACCIDENTID NOT IN (
    SELECT ACCIDENTID
    FROM ACCIDENTINFO
);

-- CarAccident -> Car
SELECT *
FROM CARACCIDENT
WHERE REGISTRATIONNO NOT IN (
    SELECT REGISTRATIONNO
    FROM CAR
);

-- BelongTo -> MaintenanceTeam
SELECT *
FROM BELONGTO
WHERE TEAMID NOT IN (
    SELECT TEAMID
    FROM MAINTENANCETEAM
);

-- BelongTo -> ResearchCenter
SELECT *
FROM BELONGTO
WHERE CENTERID NOT IN (
    SELECT CENTERID
    FROM RESEARCHCENTER
);

-- Deleting the passenger with the invalid PassengerID
DELETE FROM PASSENGER
WHERE PASSENGERID = 'U163';

-- Amending the AccidentInfo row with invalid ErrorCode
UPDATE ACCIDENTINFO
SET ERRORCODE = 'Error001'
WHERE ACCIDENTID = 'A2000' AND ERRORCODE = 'Error010';

-- Viewing the updated row
SELECT *
FROM ACCIDENTINFO
WHERE ACCIDENTID = 'A2000';

COMMIT;

-- Now checking for NULLs in the tables

SELECT *
FROM BOOKING
WHERE BOOKINGID IS NULL 
OR PASSENGERID IS NULL 
OR REGISTRATIONNO IS NULL
OR BOOKINGDATE IS NULL
OR DEPARTUREZONE IS NULL
OR DESTINATIONZONE IS NULL;

SELECT *
FROM PASSENGER
WHERE PASSENGERID IS NULL 
OR FACULTYID IS NULL
OR PASSENGERNAME IS NULL
OR PASSENGERROLE IS NULL
OR PASSENGERGENDER IS NULL
OR PASSENGERAGE IS NULL;

SELECT *
FROM CAR
WHERE REGISTRATIONNO IS NULL
OR CARMODEL IS NULL
OR MANUFACTURINGYEAR IS NULL
OR CARBODYTYPE IS NULL
OR NUMSEATS IS NULL;

SELECT *
FROM MAINTENANCE
WHERE MAINTENANCEID IS NULL
OR REGISTRATIONNO IS NULL
OR MAINTENANCEDATE IS NULL
OR MAINTENANCETYPE IS NULL
OR MAINTENANCECOST IS NULL
OR TEAMID IS NULL;

-- NULL here
SELECT *
FROM ACCIDENTINFO
WHERE ACCIDENTID IS NULL
OR ACCIDENTZONE IS NULL
OR CAR_DAMAGE_SEVERITY IS NULL
OR ERRORCODE IS NULL;

SELECT *
FROM CARACCIDENT
WHERE REGISTRATIONNO IS NULL
OR ACCIDENTID IS NULL;

SELECT *
FROM BELONGTO
WHERE TEAMID IS NULL
OR CENTERID IS NULL;

-- There are no CarAccidents with NULL values in the tables.
-- Investigating if there are any CarAccidents with AccidentIDs that dont exist in the AccidentInfo table
SELECT *
FROM CARACCIDENT
WHERE ACCIDENTID NOT IN (
    SELECT ACCIDENTID
    FROM ACCIDENTINFO
);

-- Checks for CARACCIDENT rows that have NULL AccidentIDs
SELECT *
FROM CARACCIDENT
WHERE ACCIDENTID IS NULL;

-- Seeing if there is another AccidentInfo row with the same data as the NULL AccidentID row
SELECT *
FROM ACCIDENTINFO
WHERE ACCIDENTZONE = 'ZoneC'
AND CAR_DAMAGE_SEVERITY = 'Severe damage'
AND ERRORCODE = 'Error005';

-- Select AccidentIDs that appear more than once in the CARACCIDENT table
SELECT ACCIDENTID, COUNT(*)
FROM CARACCIDENT
GROUP BY ACCIDENTID
HAVING COUNT(*) > 1;

-- Deleting the AccidentInfo row with the NULL AccidentID
DELETE FROM ACCIDENTINFO
WHERE ACCIDENTID IS NULL;

-- Checking that it is gone
SELECT *
FROM ACCIDENTINFO
WHERE ACCIDENTID IS NULL;

---------------------------------------------

-- Checks for AccidentInfo rows that do not involve a car
SELECT *
FROM ACCIDENTINFO
WHERE ACCIDENTID NOT IN (
    SELECT ACCIDENTID
    FROM CARACCIDENT
);

-- Removing AccidentID A2000
DELETE FROM ACCIDENTINFO
WHERE ACCIDENTID = 'A2000';

-- Checking that it is gone
SELECT *
FROM ACCIDENTINFO
WHERE ACCIDENTID = 'A2000';

----------------------------------------------
-- Looking for other relationship issues

-- Checking that every MaintenanceTeam has a ResearchCenter
SELECT *
FROM MAINTENANCETEAM
WHERE TEAMID NOT IN (
    SELECT TEAMID
    FROM BELONGTO
);

-- Checking if there are any passengers with no bookings
SELECT *
FROM PASSENGER
WHERE PASSENGERID NOT IN (
    SELECT PASSENGERID
    FROM BOOKING
);

-- Checking if there are any cars with no bookings
SELECT *
FROM CAR
WHERE REGISTRATIONNO NOT IN (
    SELECT REGISTRATIONNO
    FROM BOOKING
);

-----------------------------------------------

-- Are there any negative maintenance costs?
SELECT *
FROM MAINTENANCE
WHERE MAINTENANCECOST < 0;

SELECT MAINTENANCECOST, COUNT(*) 
FROM MAINTENANCE
GROUP BY MAINTENANCECOST
ORDER BY MAINTENANCECOST;

-- Amending MaintenanceID M2000 to have cost of 200
UPDATE MAINTENANCE
SET MAINTENANCECOST = 200
WHERE MAINTENANCEID = 'M2000';

SELECT * FROM MAINTENANCE
WHERE MAINTENANCEID = 'M2000';

-- Potentially impossible passenger ages
SELECT *
FROM PASSENGER
WHERE PASSENGERAGE IS NULL
OR PASSENGERAGE < 18
OR PASSENGERAGE > 100;

-- Invalid car values
SELECT *
FROM CAR
WHERE NUMSEATS <= 0
OR MANUFACTURINGYEAR < 1900;

-- Car cannot be booked before it was manufactured
SELECT *
FROM BOOKING b
WHERE b.REGISTRATIONNO IN (
    SELECT c.REGISTRATIONNO
    FROM CAR c
    WHERE b.BOOKINGDATE < TO_DATE(c.MANUFACTURINGYEAR, 'YYYY')
);

-- Maintenance cannot be performed on a car before it was manufactured
SELECT *
FROM MAINTENANCE m
WHERE m.REGISTRATIONNO IN (
    SELECT c.REGISTRATIONNO
    FROM CAR c
    WHERE m.MAINTENANCEDATE < TO_DATE(c.MANUFACTURINGYEAR, 'YYYY')
);

------------------------------------

-- Check if there are duplicate booking rows for the same passenger and car on the same date
SELECT PASSENGERID, REGISTRATIONNO, BOOKINGDATE, COUNT(*)
FROM BOOKING
GROUP BY PASSENGERID, REGISTRATIONNO, BOOKINGDATE
HAVING COUNT(*) > 1;

-- Checking if there are duplicate maintenance rows for the same car on the same date 
SELECT REGISTRATIONNO, MAINTENANCEDATE, MAINTENANCETYPE, COUNT(*)
FROM MAINTENANCE
GROUP BY REGISTRATIONNO, MAINTENANCEDATE, MAINTENANCETYPE
HAVING COUNT(*) > 1
ORDER BY REGISTRATIONNO, MAINTENANCEDATE, MAINTENANCETYPE;

SELECT MAINTENANCEID, REGISTRATIONNO, MAINTENANCEDATE, TO_CHAR(MAINTENANCEDATE, 'HH24:MI') AS MAINTENANCETIME, MAINTENANCETYPE, MAINTENANCECOST, TEAMID
FROM MAINTENANCE
WHERE REGISTRATIONNO = 'Car13'
AND MAINTENANCEDATE = TO_DATE('19/JUL/2015', 'DD/MON/YYYY');

----------------------------------------------

SELECT TO_CHAR(BOOKINGDATE, 'YYYY-MM-DD HH24:MI:SS') AS BOOKINGDATE, COUNT(*) AS BOOKINGCOUNT
FROM BOOKING
GROUP BY TO_CHAR(BOOKINGDATE, 'YYYY-MM-DD HH24:MI:SS');

SELECT TO_CHAR(MAINTENANCEDATE, 'YYYY-MM-DD HH24:MI:SS') AS MAINTENANCEDATE, COUNT(*) AS MAINTENANCECOUNT
FROM MAINTENANCE
GROUP BY TO_CHAR(MAINTENANCEDATE, 'YYYY-MM-DD HH24:MI:SS');